# Generated by Django 5.0.1 on 2024-02-13 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_receptionist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='name',
        ),
        migrations.AddField(
            model_name='doctors',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='doctor_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctors',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='doctor_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='receptionist_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='receptionist_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
