# Generated by Django 5.0.1 on 2024-02-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0005_doctors_is_active_doctors_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='User',
        ),
    ]
