# Generated by Django 5.0.1 on 2024-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_doctors_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=122)),
                ('department', models.CharField(max_length=122)),
                ('mln', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(max_length=200)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
