# Generated by Django 5.0.1 on 2024-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_doctors_remove_receptionist_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=122)),
                ('weight', models.CharField(max_length=122)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('admission_date', models.DateField()),
                ('time', models.TimeField()),
                ('phone', models.CharField(max_length=122)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
