# Generated by Django 5.0.1 on 2024-02-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
        model_name='patient',
        name='patient_id',
        field=models.AutoField(default=1, primary_key=True, serialize=False),
        preserve_default=False,
    ),
    ]