# Generated by Django 5.0.1 on 2024-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_patient_id_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
