# Generated by Django 5.0.1 on 2024-02-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='name',
            field=models.CharField(max_length=122),
        ),
    ]
