# Generated by Django 5.0.1 on 2024-04-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_temp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinical_summary_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection', models.CharField(max_length=122)),
                ('saline', models.CharField(max_length=122)),
                ('description', models.CharField(max_length=1222)),
            ],
        ),
    ]
