# Generated by Django 5.0.1 on 2024-04-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_clinical_summary_data_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinical_summary_data',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='clinical_summary_data',
            name='patient_name',
        ),
    ]
