# Generated by Django 5.0.1 on 2024-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_clinical_summary_data_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinical_summary_data',
            name='patient_id',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinical_summary_data',
            name='patient_name',
            field=models.CharField(default=2, max_length=122),
            preserve_default=False,
        ),
    ]
