# Generated by Django 5.0.1 on 2024-04-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_general_examination_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=122)),
                ('patient_name', models.CharField(max_length=122)),
                ('Details', models.CharField(max_length=122)),
            ],
        ),
    ]
