# Generated by Django 5.0.1 on 2024-04-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_previous_investigation_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatment_in_hospital_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=122)),
                ('patient_name', models.CharField(max_length=122)),
                ('Details', models.CharField(max_length=1222)),
            ],
        ),
    ]
