# Generated by Django 5.0.1 on 2024-04-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_clinical_progress_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(max_length=50)),
                ('quantity_morning', models.IntegerField(default=0)),
                ('quantity_afternoon', models.IntegerField(default=0)),
                ('quantity_evening', models.IntegerField(default=0)),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tablet')),
            ],
        ),
    ]
