# Generated by Django 5.0.1 on 2024-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_tablet_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='quantity_afternoon',
            new_name='afternoon',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='quantity_evening',
            new_name='evening',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='quantity_morning',
            new_name='morning',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='timing',
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.IntegerField(default=0),
        ),
    ]
