# Generated by Django 5.0.1 on 2024-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_quantity_afternoon_prescription_afternoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient_id',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='tablet',
            field=models.CharField(max_length=122),
        ),
    ]
